### ISSUE TITLE
Typing issues

### ISSUE THREAD

**Issue by vgoklani** [nkbt/react-debounce-input#8] opened 2015-10-22 19:47 UTC
Hi,

Thanks for taking the time to write this component!

I've run into an issue, where when the user types very fast, the characters just disappear (i.e. get lost), which results in them having to erase the text and retype.

For example, when typing "debounce", they would type d-e-b-o and then the cursor will jump, and they would see "d-e".

Presumably it's a timing issue, but I'm not sure how to fix this. Here is my code snippet:

React.createElement(DebounceInput, {debounceTimeout:300, minLength:1, autoFocus:true, key: "searchBar", type:"search", className:"form-control", value:this.state.searchString, onChange:this.handleChange })

Thanks!

**Comment by nkbt** [comment] 2015-10-22 20:42
This is something weird, I can't reproduce this on the demo page
http://nkbt.github.io/react-debounce-input/example/

And here too: http://codepen.io/nkbt/pen/VvmzLQ?editors=101

I believe it might be somehow related to `this.handleChange` implementation.

Can you please update Codepen demo to reproduce the case?

Thank you!

**Comment by vgoklani** [comment] 2015-10-22 21:29
hmm, here is my handleChange:

	handleChange: function(e) {
		this.setState({
			searchString: e,
			searchUpdated: true
		});
	},

I need to maintain the state of "searchString", but perhaps it's triggering a re-render since this is the "value" argument in:

React.createElement(DebounceInput, {debounceTimeout:300, minLength:1, autoFocus:true, key: "searchBar", type:"search", className:"form-control", value:this.state.searchString, onChange:this.handleChange })

What's a better approach for storing the searchString?  I didn't have this issue when I used a plain text box... Thanks for your help!

**Comment by nkbt** [comment] 2015-10-22 22:11
So far it does not seem odd.

I have two suggestions:

1. That might be somehow related to the type "search". 
2. It also may be related to your browser's stored data. Try adding `autoComplete="off"`, that may help.

I still can't reproduce this in the Codepen example. I tried latest Firefox and Chrome.

**Comment by nkbt** [comment] 2015-10-22 22:13
Do you have any browser plugins? Try to check it in incognito mode without any plugins.

Also, please, please, make a Codepen demo to reproduce the case (simply fork the one above and update with your code). I'm not really able to fix something without ability to reproduce it =(

**Comment by nkbt** [comment] 2015-12-10 13:29
Might be fixed by https://github.com/nkbt/react-debounce-input/pull/13

Feel free to open again if you still have this issue.

**Closed by nkbt** 2015-12-10 13:29 UTC
