### ISSUE TITLE
How to set focuse automatically

### ISSUE THREAD

**Issue by heritechie** [nkbt/react-debounce-input#77] opened 2017-09-08 13:34 UTC
Great library, but i still not getting focus automatically after specific event occur

```
someEvent(product) {
    this.srcInput.focus();
 }


<DebounceInput
                  autoFocus
                  ref={(input) => this.srcInput = input}
                  debounceTimeout={500}
                  type="text"
                  name="q"
                  autoComplete="off" />
```
getting error in console

`Uncaught TypeError: this.srcInput.focus is not a function`

Is there any suggestion to solve ?

**Comment by nkbt** [comment] 2017-09-11 02:07
Since DebounceInput is a custom component and not element, assigning ref would not give you back DOM element. But the need for actual DOM element is understandable...

I am closing this issue as duplicate of https://github.com/nkbt/react-debounce-input/issues/65 (see some more details there and some ideas around how it might get fixed)

**Closed by nkbt** 2017-09-11 02:07 UTC
Labels: duplicate

**Comment by heritechie** [comment] 2017-09-11 03:02
Ok @nkbt , thanks for suggestion,
