### ISSUE TITLE
onChange handler called on Enter and once again after debounceTimeout

### ISSUE THREAD

**Issue by isaacalves** [nkbt/react-debounce-input#64] opened 2017-02-24 08:17 UTC
I'm using something like this:

`
	handleInputChange(e) {
		this.props.onInputChange(e.target.value);
	}
`

and on my render method:

`
       		<DebounceInput type='text'
       			onChange={ this.handleInputChange.bind(this) }
		        debounceTimeout={ 1000 }
       		/>
`

I see that `handleInputChange` is also called when I press Enter from the input field (although I could handle that myself in an `onSubmit` handler on the form). I assume that's intended, but why then does `handleInputChange` fires again after the timeout? 

Scenario:

1. focus on text field
2. type something and press Enter
3. handleInputChange() is called immediately
4. handleInputChange() is called again after the timeout

I see that I can use `forceNotifyByEnter` so it's not called on Enter key press. That solves the problem, but actually it would be nice to have it being called on Enter key press as well, as long as it clears the timeout.

**Comment by emhagman** [comment] 2017-03-10 16:15
+1

**Comment by nkbt** [comment] 2017-04-13 03:42
Makes sense. I would be happy to accept a PR on this

**Comment by hozefaj** [comment] 2017-05-12 23:15
Let me give this is a shot. Since I am getting bugs filed on me for this issue.

**Comment by hozefaj** [comment] 2017-05-12 23:16
Let me take a crack at fixing this.

**Comment by nkbt** [comment] 2017-05-14 00:10
Thanks @hozefaj! Timeout should be cancelled on Enter, that feels like the most logical way.

**Comment by Data-Meister** [comment] 2017-06-29 16:22
This is an issue with both notify on enter, and also notify on blur. 

The problem is [this line ](https://github.com/nkbt/react-debounce-input/blob/master/src/Component.js#L101)

`this.notify` is a method, but the code is attempting to access a property `this.notify.cancel` as if `this.notify` were an object

**Comment by nkbt** [comment] 2017-06-29 18:05
That is ok, since lodash.debounce has .cancel method available ondebounced functions

**Comment by Data-Meister** [comment] 2017-06-30 14:57
In that case, the problem is `this.notify` is not itself a debounced function. The debounced function is called from within `this.notify`

```
 const debouncedChangeFunc = debounce(event => {
        this.isDebouncing = false;
        this.doNotify(event);
      }, debounceTimeout);

      this.notify = event => {
        this.isDebouncing = true;
        debouncedChangeFunc(event);
      };
    }
```

**Comment by Data-Meister** [comment] 2017-07-20 16:54
I've now fixed this bug, with code submitted as part of this PR

https://github.com/nkbt/react-debounce-input/pull/73

**Comment by nkbt** [comment] 2017-08-03 00:22
Should be fixed in `react-debounce-input@3.0.1`

**Closed by nkbt** 2017-08-03 00:22 UTC
Labels: bug
